---
abstract: "compare two XML files for equivalency, in an ordered\nfashion."
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-XML-Ordered
requires:
  Exporter: 0
  Test::More: 0
  XML::LibXML::Reader: 0
  base: 0
  strict: 0
  vars: 0
  warnings: 0
resources:
  repository: ssh://hg@bitbucket.org/shlomif/test-xml-ordered
version: 0.0.2
